image: docker:latest

services:
— docker:dind

variables:
DOCKER_DRIVER: overlay2
DOCKER_IMAGE_NAME: $CI_REGISTRY_USER/tauekel

before_script:
— echo “$CI_REGISTRY_PASSWORD” | docker login -u “$CI_REGISTRY_USER” — password-stdin

build:
stage: build
script:
— docker build -t $DOCKER_IMAGE_NAME:latest .
— docker push $DOCKER_IMAGE_NAME:latest