stages:
  - build

variables:
  DOCKER_IMAGE_NAME: thelightcome/tauekel

build:
  image: docker:latest
  stage: build
  interruptible: true
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY
    # - echo "$CI_REGISTRY_PASSWORD" | docker login $DOCKER_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    — docker build -t "$DOCKER_IMAGE_NAME":latest .
    — docker push "$DOCKER_IMAGE_NAME":latest