stages:
  - build

variables:
  DOCKER_IMAGE_NAME: thelightcome/tauekel

build:
  image: docker:latest
  stage: build
  interruptible: true
  only:
    - master
  services:
    - docker:dind
  before_script:
    - echo dckr_pat_f_5ZrMGgcxvU4vvmkjaUqA3uNZc | docker login "$DOCKER_REGISTRY" --username thelightcome --password-stdin
  script:
    — docker build -t $DOCKER_IMAGE_NAME:latest .
    — docker push $DOCKER_IMAGE_NAME:latest