stages:
  - build

variables:
  DOCKER_IMAGE_NAME: thelightcome/tauekel

build:
  image: docker:latest
  stage: build
  interruptible: true
  only:
    - master
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $DOCKER_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    — docker build --pull -t thelightcome/tauekel:latest .
    — docker push thelightcome/tauekel:latest