variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: CI_REGISTRY_USER/tauekel
  CI_REGISTRY: tauekel

build:
  image: docker:latest
  stage: build
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    — docker build -t $DOCKER_IMAGE_NAME:latest .
    — docker push $DOCKER_IMAGE_NAME:latest