version: '3.9'
services:
  tauekel_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_API_BASE: 'https://tauekel-cargo-80dad368bb22.herokuapp.com/api/'
    container_name: tauekel_frontend
    ports:
      - 80:3000