export default {
	welcome: 'Hello',
	levels: {
		BRONZE: {
			name: 'Bronze',
		},
		SILVER: {
			name: 'Silver',
		},
		GOLD: {
			name: 'Gold',
		},
		PLATINUM: {
			name: 'Platinum',
		},
		DIAMOND: {
			name: 'Diamond',
		},
		NONE: {
			name: 'Beginner',
		},
	},
	data: {
		main: {
			bannerTitle: 'Welcome to <span>iPost.kz</span>',
			bannerText: 'Quick and affordable delivery of goods from China',
			steps: {
				'1': 'By registering here, you will receive your foreign addresses',
				'2': 'Shop in brand stores using the received addresses',
				'3': 'Add the expected package in your personal account',
				'4': 'Receive your package at the branch within 7-14 days',
			},
			address:
				'Kalkaman-2 district, Karakulova street, 40 house, 4th floor. 050006 \n Almaty, Kazakhstan',
		},
	},
	our_whatsapp: 'Our WhatsApp group',
	titles: {
		faq: 'FAQ',
		addProduct: 'Add Product',
		locations: 'Locations',
		branches: 'Branches',
		personal: 'Managers',
		users: 'Users',
		products: 'Products',
		checkProduct: 'Track Product',
		contacts: 'Contacts',
		ourBranches: 'Our Branches',
		tariffs: 'Tariff',
		how_is_work: 'How it works',
	},
	pages: {
		login: 'Login',
		register: 'Register',
		user: 'Products',
		profile: 'My Profile',
		productList: 'My Products',
		address: 'My Address',
		info: 'Info',
		calculation: 'Calculator',
		locations: 'Locations',
		branchs: 'Branches',
		personals: 'Managers',
		products: 'Products',
		users: 'Users',
		checkProduct: 'Track Product',
		settings: 'Settings',
		settingsChange: 'Edit Data',
		archive: 'Archive',
		lessons: 'Lessons',
		contacts: 'Contacts',
		referrals: 'Referrals',
	},
	labels: {
		writeWhatapp: 'Write to WhatsApp',
		viewInstagram: 'All news on Instagram',
		writeTelegram: 'Need help, write to Telegram',
		getAddress: 'Get Address',
		list_of_cancel_products: 'List of prohibited goods',
		days: '{0} days',
		timeDeliver: 'Delivery time',
		cost_to_mass: '{0}tg / 1 kg',
		cost_and_mass: 'Price/weight',
		filter: 'Filter',
		all: 'All',
		yes: 'Yes',
		no: 'No',
		level: 'Level',
		active: 'Active',
		fullName: 'Full Name',
		referrals: 'Referrals',
		referer: 'Referrer',
		promoCode: 'Promo Code',
		user: 'User',
		registerMsg: 'Register',
		firstName: 'First Name',
		lastName: 'Last Name',
		email: 'E-mail',
		phoneNumber: 'Phone Number',
		password: 'Password',
		userId: 'User ID',
		confirmPassword: 'Confirm Password',
		selectCity: 'Select City',
		selectBranch: 'Select Branch',
		trackCode: 'Track Code',
		description: 'Description',
		massCount: 'Weight (kg)',
		rate: 'Exchange Rate',
		productMass: 'Product Weight',
		cityName: 'City Name',
		cityType: 'City Location',
		branch: 'Branch',
		branchName: 'Branch Name',
		branchAddress: 'Branch Address',
		branchDescription: 'Full Address',
		address: 'Address',
		city: 'City',
		unlock: 'Unlock',
		lock: 'Lock',
		autoFetch: 'Enable AUTO Registration',
		shop: 'New',
		changePassword: 'Change Password',
		yourCode: 'Your Code',
		dateArrive: 'Arrival Date',
		commands: 'Commands',
		totalCount: 'Total',
		search: 'Search',
		code: 'Local Area Code',
	},
	commands: {
		submit: 'Submit',
		logout: 'Logout',
		clear: 'Clear',
		select: 'Select',
		update: 'Update',
		goBack: 'Go Back',
		toMainPage: 'Main Page',
		copy: 'Copy',
		change: 'Change',
		cancel: 'Cancel',
		save: 'Save',
		add: 'Add',
		selectUser: 'Select User',
		archive: 'To Archive',
		delete: 'Delete',
		backArchive: 'Return from Archive',
		backTo: 'Back',
		view: 'View',
	},
	messages: {
		successUpdateData: 'Your data has been updated!',
		successRegister: 'You have successfully registered!',
		successProductAdd: 'Product added successfully!',
		successLocationCreate: 'Location added successfully!',
		successLocationRemove: 'Location deleted successfully',
		successBranchCreate: 'Branch created successfully',
		successBranchRemove: 'Branch deleted successfully',
		successAdminCreate: 'Manager created successfully',
		successAdminRemove: 'Manager deleted successfully',
		noData: 'No data',
		someUnexceptableError: 'Oops... An unexpected error occurred',
		successProductRegistered: 'Product registered',
		loginError: 'Did you enter the wrong password?',
		pageNotFound: 'Page not found',
	},
	places: {
		CHINA: 'In China',
		BORDER: 'At the Border',
		KZ: 'In Kazakhstan',
		NULL: 'In the Store',
	},
	errors: {
		Required: 'This field is required',
		'The passwords did not match': 'The passwords did not match',
		'Invalid email': 'Invalid email',
		'Invalid input': 'Invalid input',
		'String must contain at most 150 character(s)':
			'The field value must not exceed 150 characters',
		'String must contain at most 700 character(s)':
			'The field value must not exceed 700 characters',
		'String must contain at most 200 character(s)':
			'The field value must not exceed 200 characters',
		'String must contain at most 500 character(s)':
			'The field value must not exceed 500 characters',
		'String must contain at least 4 character(s)':
			'The field value must be at least 4 characters',
		'String must contain at least 10 character(s)':
			'The field value must be at least 10 characters',
		'String must contain at least 1 character(s)':
			'The field value must be at least 1 character',
		maxMass: 'The specified value exceeds the maximum allowable value',
		'Phone number is already in use!': 'The specified number is not available!',
	},
}
