export default {
  welcome: 'Hello',
  titles: {
    faq: 'FAQ',
    addProduct: 'Adding a product',
    locations: 'Localities',
    branches: 'Branches',
    personal: 'Managers',
    checkProduct: 'Product tracking'
  },
  pages: {
    login: 'Sign in',
    register: 'Sigh up',
    user: 'Adding a product',
    productList: 'List of my products',
    info: 'Information about the branch',
    calculation: 'Calculator',
    locations: 'Localities',
    branchs: 'Branches',
    personals: 'Managers',
    products: 'Products',
    users: 'Users',
    checkProduct: 'Product tracking',
    settings: 'Settings',
  },
  labels: {
    registerMsg: 'Registration',
    firstName: 'Name',
    lastName: 'Surname',
    email: 'E-mail',
    phoneNumber: 'Phone number',
    password: 'Password',
    confirmPassword: 'Repeat password',
    selectCity: 'Select a locality',
    selectBranch: 'Select a branch',
    trackCode: 'Track code',
    description: 'Description',
    massCount: 'Weight (kg)',
    rate: 'Currency exchange rate',
    productMass: 'Product weight',
    cityName: 'Name of the settlement',
    cityType: 'Location of the settlement',
    branchName: 'Name of the branch',
    branchAddress: 'Branch address',
    city: 'City',
    unlock: 'Unlock',
    lock: 'Block',
    autoFetch: 'Enable auto-registration',
  },
  commands: {
    submit: 'Send',
    logout: 'Exit',
    clear: 'Clear',
    select: 'Choose',
    update: 'Update',
    goBack: 'Go back',
  },
  messages: {
    successRegister: 'You have registered successfully!',
    successProductAdd: 'The locality has been successfully created',
    successLocationRemove: 'The locality has been successfully deleted',
    successBranchCreate: 'The branch has been successfully created',
    successBranchRemove: 'The branch was successfully deleted',
    successAdminCreate: 'The manager has been successfully created',
    successAdminRemove: 'The manager was successfully deleted',
    noData: 'No data available',
    someUnexceptableError: 'Oops... An unexpected error has occurred',
    successProductRegistered: 'The product is registered'
  },
  places: {
    CHINA: 'In China',
    BORDER: 'On the border',
    KZ: 'In Kazakhstan',
  }
}
