export default {
	welcome: 'Hello',
	our_whatsapp: 'Our WhatsApp group',
	titles: {
		faq: 'FAQ',
		addProduct: 'Adding a product',
		locations: 'Localities',
		branches: 'Branches',
		personal: 'Managers',
		users: 'Users',
		products: 'Products',
		checkProduct: 'Product tracking',
		contacts: 'Contacts',
	},
	pages: {
		login: 'Sign in',
		register: 'Sigh up',
		user: 'Main',
		productList: 'Products',
		address: 'Address',
		info: 'Info',
		calculation: 'Calculator',
		locations: 'Localities',
		branchs: 'Branches',
		personals: 'Managers',
		products: 'Products',
		users: 'Users',
		checkProduct: 'Product tracking',
		settings: 'Settings',
		archive: 'Archive',
		lessons: 'Lessons',
		contacts: 'Contacts',
	},
	labels: {
		user: 'User',
		registerMsg: 'Registration',
		firstName: 'Name',
		lastName: 'Surname',
		email: 'E-mail',
		phoneNumber: 'Phone number',
		password: 'Password',
		confirmPassword: 'Repeat password',
		selectCity: 'Locality',
		selectBranch: 'Pick-up point',
		trackCode: 'Track code',
		description: 'Description',
		massCount: 'Weight (kg)',
		rate: 'Currency exchange rate',
		productMass: 'Product weight',
		cityName: 'Name of the settlement',
		cityType: 'Location of the settlement',
		branchName: 'Name of the branch',
		branchAddress: 'Branch address',
		branchDescription: 'Full address',
		city: 'City',
		unlock: 'Unlock',
		lock: 'Block',
		autoFetch: 'Enable auto-registration',
		shop: 'In the shop',
		commands: 'Commands',
		totalCount: 'Total',
		search: 'Search',
		code: 'Locality code',
	},
	commands: {
		submit: 'Send',
		logout: 'Exit',
		clear: 'Clear',
		select: 'Choose',
		update: 'Update',
		goBack: 'Go back',
		toMainPage: 'To main',
		selectUser: 'Select user',
		archive: 'To the archive',
		delete: 'Delete',
		backArchive: 'Return from archive',
		backTo: 'Back',
	},
	messages: {
		successRegister: 'You have registered successfully!',
		successProductAdd: 'The product has been successfully added!',
		successLocationCreate: 'The locality has been added successfully!',
		successLocationRemove: 'The locality has been successfully deleted',
		successBranchCreate: 'The branch has been successfully created',
		successBranchRemove: 'The branch was successfully deleted',
		successAdminCreate: 'The manager has been successfully created',
		successAdminRemove: 'The manager was successfully deleted',
		noData: 'No data available',
		someUnexceptableError: 'Oops... An unexpected error has occurred',
		successProductRegistered: 'The product is registered',
		loginError: 'You entered the wrong password',
		pageNotFound: 'Page not found',
	},
	places: {
		CHINA: 'In China',
		BORDER: 'On the border',
		KZ: 'In Kazakhstan',
		NULL: 'In the shop',
	},
	errors: {
		Required: 'This field is required',
		'The passwords did not match': "Passwords don't match",
		'Invalid email': 'Invalid email',
		'Invalid input': 'Invalid field format',
		'String must contain at most 150 character(s)':
			'The string must contain no more than 150 characters',
		'String must contain at most 700 character(s)':
			'The string must contain no more than 700 characters',
		'String must contain at most 200 character(s)':
			'The string must contain no more than 200 characters',
		'String must contain at most 500 character(s)':
			'The string must contain no more than 500 characters',
		'String must contain at least 4 character(s)':
			'The string must contain at least 4 characters',
		'String must contain at least 10 character(s)':
			'The string must contain at least 10 characters',
		maxMass: 'The specified value exceeds the maximum allowed value',
	},
}
