export default {
	welcome: 'Сәлем',
	levels: {
		BRONZE: {
			name: 'Қола',
		},
		SILVER: {
			name: 'Күміс',
		},
		GOLD: {
			name: 'Алтын',
		},
		PLATINUM: {
			name: 'Платина',
		},
		DIAMOND: {
			name: 'Гауһар',
		},
		NONE: {
			name: 'Жаңадан бастаушы',
		},
	},
	data: {
		main: {
			bannerTitle: 'iPost.kz сайтына <span>қош келдіңіз</span>',
			bannerText: 'Қытайдан тауарларды жылдам және қолжетімді жеткіземіз',
			steps: {
				'1': 'Мұнда тіркелу арқылы сіз шетелдік мекенжайларды аласыз',
				'2': 'Алынған мекенжайларды енгізіп, фирмалық дүкендерден сатып аласыз',
				'3': 'Жеке кабинетте күтілетін сәлемдемені қосасыз',
				'4': 'Сәлемдемеңізді филиалдан 7-14 күн ішінде аласыз',
			},
			address:
				'Қалқаман-2 шағын ауданы, Қарақулова көш., 40 үй, 4 этаж. 050006 \n Алматы, Қазақстан',
		},
	},
	our_whatsapp: 'Біздің WhatsApp тобымыз',
	titles: {
		faq: 'FAQ',
		addProduct: 'Өнімді қосу',
		locations: 'Елді мекендер',
		branches: 'Филиалдар',
		personal: 'Менеджерлер',
		users: 'Пайдаланушылар',
		products: 'Тауарлар',
		checkProduct: 'Тауарды бақылау',
		contacts: 'Контактілер',
		ourBranches: 'Біздің филиалдар',
		tariffs: 'Тариф',
		how_is_work: 'Бұл қалай жұмыс істейді',
	},
	pages: {
		login: 'Кіру',
		register: 'Регистрация',
		user: 'Тауарлар',
		profile: 'Менің профилім',
		productList: 'Менің тауарларым',
		address: 'Менің мекен-жайым',
		info: 'Инфо',
		calculation: 'Калькулятор',
		locations: 'Елді мекендер',
		branchs: 'Филиалдар',
		personals: 'Менеджерлер',
		products: 'Өнімдер',
		users: 'Пайдаланушылар',
		checkProduct: 'Тауарды бақылау',
		settings: 'Параметрлер',
		settingsChange: 'Деректерді өңдеу',
		archive: 'Мұрағат',
		lessons: 'Сабақтар',
		contacts: 'Контактілер',
		referrals: 'Жолдамалар',
	},
	labels: {
		writeWhatapp: 'WhatsApp-қа жазу',
		viewInstagram: 'Барлық жаңалықтар Instagram-да',
		writeTelegram: 'Көмек керек болса, Telegram-ға жазыңыз',
		getAddress: 'Мекенжай алу',
		list_of_cancel_products: 'Тыйым салынған тауарлар тізімі',
		days: '{0} күн',
		timeDeliver: 'Жеткізу уақыты',
		cost_to_mass: '{0}тг / 1 кг',
		cost_and_mass: 'Баға/салмақ',
		filter: 'Фильтр',
		all: 'Барлығы',
		yes: 'Иа',
		no: 'Жоқ',
		level: 'Деңгей',
		active: 'Белсенді',
		fullName: 'Аты-жөні',
		referrals: 'Жолдамалар',
		referer: 'Реферер',
		promoCode: 'Промокод',
		user: 'Пайдаланушы',
		registerMsg: 'Тіркеу',
		firstName: 'Аты',
		lastName: 'Тегі',
		email: 'E-mail',
		phoneNumber: 'Телефон нөмірі',
		password: 'Құпия сөз',
		userId: 'Пайдаланушының ID',
		confirmPassword: 'Құпия сөзді қайталау',
		selectCity: 'Елді мекен',
		selectBranch: 'Қабылдау пункті',
		trackCode: 'Трек коды',
		description: 'Сипаттама',
		massCount: 'Салмағы (кг)',
		rate: 'Валюта бағамы',
		productMass: 'Өнімнің салмағы',
		cityName: 'Елді мекеннің атауы',
		cityType: 'Елді мекеннің орналасқан жері',
		branch: 'Филиал',
		branchName: 'Филиалдың атауы',
		branchAddress: 'Филиалдың мекенжайы',
		branchDescription: 'Толық мекенжайы',
		address: 'Мекенжай',
		city: 'Қала',
		unlock: 'Құлпын ашу',
		lock: 'Бұғаттау',
		autoFetch: 'АВТО тіркеуді қосыңыз',
		shop: 'Жаңа',
		changePassword: 'Құпиясөзді өзгерту',
		yourCode: 'Сіздің кодыңыз',
		dateArrive: 'Келген күні',
		commands: 'Командалар',
		totalCount: 'Барлығы',
		search: 'Іздеу',
		code: 'Жергілікті жер коды',
	},
	commands: {
		submit: 'Жіберу',
		logout: 'Шығу',
		clear: 'Тазалау',
		select: 'Таңдау',
		update: 'Жаңарту',
		goBack: 'Артқа қайту',
		toMainPage: 'Басты бет',
		copy: 'Көшіру',
		change: 'Өзгерту',
		cancel: 'Бас тарту',
		save: 'Сақтау',
		add: 'Қосу',
		selectUser: 'Пайдаланушыны таңдаңыз',
		archive: 'Мұрағатқа',
		delete: 'Өшіру',
		backArchive: 'Мұрағаттан қайтару',
		backTo: 'Артқа',
		view: 'Көрсету',
	},
	messages: {
		successUpdateData: 'Мәліметтеріңіз жаңартылды!',
		successRegister: 'Сіз сәтті тіркеуден өттіңіз!',
		successProductAdd: 'Өнім сәтті қосылды!',
		successLocationCreate: 'Елді мекен сәтті қосылды!',
		successLocationRemove: 'Елді мекен сәтті жойылды',
		successBranchCreate: 'Филиал сәтті құрылды',
		successBranchRemove: 'Филиал сәтті жойылды',
		successAdminCreate: 'Менеджер сәтті құрылды',
		successAdminRemove: 'Менеджер сәтті жойылды',
		noData: 'Деректер жоқ',
		someUnexceptableError: 'Ой... Күтпеген қате пайда болды',
		successProductRegistered: 'Тауар тіркелген',
		loginError: 'Сіз қате құпия сөзді енгіздіңіз бе',
		pageNotFound: 'Бет табылмады',
	},
	places: {
		CHINA: 'Қытайда',
		BORDER: 'Шекарада',
		KZ: 'Қазақстанда',
		NULL: 'Дүкенде',
	},
	errors: {
		Required: 'Бұл өріс міндетті болып табылады',
		'The passwords did not match': 'Құпия сөздер бірдей емес',
		'Invalid email': 'Жарамсыз электрондық почта',
		'Invalid input': 'Өріс мәні жарамсыз',
		'String must contain at most 150 character(s)':
			'Өріс мәні 150 таңбадан аспауы керек',
		'String must contain at most 700 character(s)':
			'Өріс мәні 700 таңбадан аспауы керек',
		'String must contain at most 200 character(s)':
			'Өріс мәні 200 таңбадан аспауы керек',
		'String must contain at most 500 character(s)':
			'Өріс мәні 500 таңбадан аспауы керек',
		'String must contain at least 4 character(s)':
			'Өріс мәні кемінде 4 таңба болуы керек',
		'String must contain at least 10 character(s)':
			'Өріс мәні кемінде 10 таңба болуы керек',
		'String must contain at least 1 character(s)':
			'Өріс мәні кемінде 1 таңба болуы керек',
		maxMass: 'Көрсетілген мән максималды рұқсат етілген мәннен асады',
		'Phone number is already in use!': 'Көрсетілген нөмір бос емес!',
	},
}
