export default {
  welcome: 'Сәлем',
  titles: {
    faq: 'FAQ',
    addProduct: 'Өнімді қосу',
    locations: 'Елді мекендер',
    branches: 'Филиалдар',
    personal: 'Менеджерлер',
    checkProduct: 'Тауарды бақылау'
  },
  pages: {
    login: 'Кіру',
    register: 'Авторизациядан өту',
    user: 'Товарды қосу',
    productList: 'Менің өнімдерімнің тізімі',
    info: 'Филиал туралы ақпарат',
    calculation: 'Калькулятор',
    locations: 'Елді мекендер',
    branchs: 'Филиалдар',
    personals: 'Менеджерлер',
    products: 'Өнімдер',
    users: 'Пайдаланушылар',
    checkProduct: 'Тауарды бақылау',
    settings: 'Параметрлер',
  },
  labels: {
    registerMsg: 'Тіркеу',
    firstName: 'Аты',
    lastName: 'Тегі',
    email: 'E-mail',
    phoneNumber: 'Телефон нөмірі',
    password: 'Құпия сөз',
    confirmPassword: 'Құпия сөзді қайталау',
    selectCity: 'елді мекенді таңдаңыз',
    selectBranch: 'Филиалды таңдаңыз',
    trackCode: 'Трек коды',
    description: 'Сипаттама',
    massCount: 'Салмағы (кг)',
    rate: 'Валюта бағамы',
    productMass: 'Өнімнің салмағы',
    cityName: 'Елді мекеннің атауы',
    cityType: 'Елді мекеннің орналасқан жері',
    branchName: 'Филиалдың атауы',
    branchAddress: 'Филиалдың мекенжайы',
    city: 'Қала',
    unlock: 'Құлпын ашу',
    lock: 'Бұғаттау',
    autoFetch: 'АВТО тіркеуді қосыңыз',
  },
  commands: {
    submit: 'Жіберу',
    logout: 'Шығу',
    clear: 'Тазалау',
    select: 'Таңдау',
    update: 'Жаңарту',
    goBack: 'Артқа қайту',
  },
  messages: {
    successRegister: 'Сіз сәтті тіркеуден өттіңіз!',
    successProductAdd: 'Елді мекен сәтті құрылды',
    successLocationRemove: 'Елді мекен сәтті жойылды',
    successBranchCreate: 'Филиал сәтті құрылды',
    successBranchRemove: 'Филиал сәтті жойылды',
    successAdminCreate: 'Менеджер сәтті құрылды',
    successAdminRemove: 'Менеджер сәтті жойылды',
    noData: 'Деректер жоқ',
    someUnexceptableError: 'Ой... Күтпеген қате пайда болды',
    successProductRegistered: 'Тауар тіркелген'
  },
  places: {
    CHINA: 'Қытайда',
    BORDER: 'Шекарада',
    KZ: 'Қазақстанда',
  }
}
