export default {
	welcome: 'Сәлем',
	our_whatsapp: 'Біздің WhatsApp тобымыз',
	titles: {
		faq: 'FAQ',
		addProduct: 'Өнімді қосу',
		locations: 'Елді мекендер',
		branches: 'Филиалдар',
		personal: 'Менеджерлер',
		users: 'Пайдаланушылар',
		products: 'Тауарлар',
		checkProduct: 'Тауарды бақылау',
		contacts: 'Контактілер',
	},
	pages: {
		login: 'Кіру',
		register: 'Регистрациядан өту',
		user: 'Басты бет',
		productList: 'Өнімдер',
		address: 'Адрес',
		info: 'Инфо',
		calculation: 'Калькулятор',
		locations: 'Елді мекендер',
		branchs: 'Филиалдар',
		personals: 'Менеджерлер',
		products: 'Өнімдер',
		users: 'Пайдаланушылар',
		checkProduct: 'Тауарды бақылау',
		settings: 'Параметрлер',
		archive: 'Мұрағат',
		lessons: 'Сабақтар',
		contacts: 'Контактілер',
		referrals: 'Жолдамалар',
	},
	labels: {
		filter: 'Фильтр',
		all: 'Барлығы',
		yes: 'Иа',
		no: 'Жоқ',
		level: 'Деңгей',
		active: 'Белсенді',
		fullName: 'Аты-жөні',
		referrals: 'Жолдамалар',
		referer: 'Реферер',
		promoCode: 'Промокод',
		user: 'Пайдаланушы',
		registerMsg: 'Тіркеу',
		firstName: 'Аты',
		lastName: 'Тегі',
		email: 'E-mail',
		phoneNumber: 'Телефон нөмірі',
		password: 'Құпия сөз',
		userId: 'Пайдаланушының ID',
		confirmPassword: 'Құпия сөзді қайталау',
		selectCity: 'Елді мекен',
		selectBranch: 'Қабылдау пункті',
		trackCode: 'Трек коды',
		description: 'Сипаттама',
		massCount: 'Салмағы (кг)',
		rate: 'Валюта бағамы',
		productMass: 'Өнімнің салмағы',
		cityName: 'Елді мекеннің атауы',
		cityType: 'Елді мекеннің орналасқан жері',
		branch: 'Филиал',
		branchName: 'Филиалдың атауы',
		branchAddress: 'Филиалдың мекенжайы',
		branchDescription: 'Толық мекенжайы',
		city: 'Қала',
		unlock: 'Құлпын ашу',
		lock: 'Бұғаттау',
		autoFetch: 'АВТО тіркеуді қосыңыз',
		shop: 'Дүкенде',
		commands: 'Командалар',
		totalCount: 'Барлығы',
		search: 'Іздеу',
		code: 'Жергілікті жер коды',
	},
	commands: {
		submit: 'Жіберу',
		logout: 'Шығу',
		clear: 'Тазалау',
		select: 'Таңдау',
		update: 'Жаңарту',
		goBack: 'Артқа қайту',
		toMainPage: 'Басты бет',
		selectUser: 'Пайдаланушыны таңдаңыз',
		archive: 'Мұрағатқа',
		delete: 'Өшіру',
		backArchive: 'Мұрағаттан қайтару',
		backTo: 'Артқа',
		view: 'Көрсету',
	},
	messages: {
		successRegister: 'Сіз сәтті тіркеуден өттіңіз!',
		successProductAdd: 'Өнім сәтті қосылды!',
		successLocationCreate: 'Елді мекен сәтті қосылды!',
		successLocationRemove: 'Елді мекен сәтті жойылды',
		successBranchCreate: 'Филиал сәтті құрылды',
		successBranchRemove: 'Филиал сәтті жойылды',
		successAdminCreate: 'Менеджер сәтті құрылды',
		successAdminRemove: 'Менеджер сәтті жойылды',
		noData: 'Деректер жоқ',
		someUnexceptableError: 'Ой... Күтпеген қате пайда болды',
		successProductRegistered: 'Тауар тіркелген',
		loginError: 'Сіз қате құпия сөзді енгіздіңіз бе',
		pageNotFound: 'Бет табылмады',
	},
	places: {
		CHINA: 'Қытайда',
		BORDER: 'Шекарада',
		KZ: 'Қазақстанда',
		NULL: 'Дүкенде',
	},
	errors: {
		Required: 'Бұл өріс міндетті болып табылады',
		'The passwords did not match': 'Құпия сөздер бірдей емес',
		'Invalid email': 'Жарамсыз электрондық почта',
		'Invalid input': 'Өріс мәні жарамсыз',
		'String must contain at most 150 character(s)':
			'Өріс мәні 150 таңбадан аспауы керек',
		'String must contain at most 700 character(s)':
			'Өріс мәні 700 таңбадан аспауы керек',
		'String must contain at most 200 character(s)':
			'Өріс мәні 200 таңбадан аспауы керек',
		'String must contain at most 500 character(s)':
			'Өріс мәні 500 таңбадан аспауы керек',
		'String must contain at least 4 character(s)':
			'Өріс мәні кемінде 4 таңба болуы керек',
		'String must contain at least 10 character(s)':
			'Өріс мәні кемінде 10 таңба болуы керек',
	},
}
