export default {
  welcome: 'Привет',
  titles: {
    faq: 'faq',
    addProduct: 'addProduct',
    locations: 'locations',
    branches: 'branches',
    personal: 'personal',
    checkProduct: 'checkProduct'
  },
  pages: {
    login: 'login',
    register: 'register',
    user: 'user',
    productList: 'productList',
    info: 'info',
    calculation: 'calculation',
    locations: 'locations',
    branchs: 'branchs',
    personals: 'personals',
    products: 'products',
    users: 'users',
    checkProduct: 'checkProduct',
    settings: 'settings',
  },
  labels: {
    registerMsg: 'Регистрация',
    firstName: 'firstName',
    lastName: 'lastName',
    email: 'email',
    phoneNumber: 'phoneNumber',
    password: 'password',
    confirmPassword: 'confirmPassword',
    warehouseId: 'warehouseId',
    selectCity: 'selectCity',
    selectBranch: 'selectBranch',
    trackCode: 'trackCode',
    description: 'description',
    massCount: 'massCount',
    rate: 'rate',
    productMass: 'productMass',
    cityName: 'cityName',
    cityType: 'cityType',
    branchName: 'branchName',
    branchAddress: 'branchAddress',
    city: 'city',
    unlock: 'unlock',
    lock: 'lock',
    autoFetch: 'autoFetch',
  },
  commands: {
    submit: 'submit',
    logout: 'Logout',
    clear: 'clear',
    select: 'select',
    update: 'update',
    goBack: 'goBack',
  },
  messages: {
    successRegister: 'successRegister',
    successProductAdd: 'successProductAdd',
    successLocationRemove: 'successLocationRemove',
    successBranchCreate: 'successBranchCreate',
    successBranchRemove: 'successBranchRemove',
    successAdminCreate: 'successAdminCreate',
    successAdminRemove: 'successAdminRemove',
    noData: 'noData',
    someUnexceptableError: 'someUnexceptableError',
    successProductRegistered: 'successProductRegistered'
  },
  places: {
    CHINA: 'CHINA',
    BORDER: 'BORDER',
    KZ: 'KZ',
  }
}
