export default {
	welcome: 'Привет',
	titles: {
		faq: 'FAQ',
		addProduct: 'Добавление товара',
		locations: 'Населенные пункты',
		branches: 'Филиалы',
		personal: 'Менеджеры',
		checkProduct: 'Трекинг товара',
	},
	pages: {
		login: 'Войти',
		register: 'Регистрация',
		user: 'Главная',
		productList: 'Товары',
		info: 'Филиал',
		calculation: 'Калькулятор',
		locations: 'Населенные пункты',
		branchs: 'Филиалы',
		personals: 'Менеджеры',
		products: 'Товары',
		users: 'Пользователи',
		checkProduct: 'Трекинг товара',
		settings: 'Кабинет',
		settingsChange: 'Редактировать данные',
	},
	labels: {
		registerMsg: 'Регистрация',
		firstName: 'Имя',
		lastName: 'Фамилия',
		email: 'E-mail',
		phoneNumber: 'Номер телефона',
		password: 'Пароль',
		confirmPassword: 'Повтор пароля',
		selectCity: 'Выбрать населенный пункт',
		selectBranch: 'Выбрать филиал',
		trackCode: 'Трек код',
		description: 'Описание',
		massCount: 'Вес (кг)',
		rate: 'Курс валюты',
		productMass: 'Вес товара',
		cityName: 'Наименование населенного пункта',
		cityType: 'Местоположение населенного пункта',
		branch: 'Филиал',
		branchName: 'Наименование филиала',
		branchAddress: 'Адрес филиала',
		address: 'Адрес',
		city: 'Город',
		unlock: 'Разблокировать',
		lock: 'Блокировать',
		autoFetch: 'Включить авторегистрацию',
		shop: 'Новые',
		changePassword: 'Сменить пароль',
		yourCode: 'Ваш номер',
	},
	commands: {
		submit: 'Отправить',
		logout: 'Выйти',
		clear: 'Очистить',
		select: 'Выбрать',
		update: 'Обновить',
		goBack: 'Вернутся назад',
		toMainPage: 'На главную',
		copy: 'Скопировать',
		change: 'Изменить',
		cancel: 'Отмена',
		save: 'Сохранить',
	},
	messages: {
		successUpdateData: 'Ваши данные обновлены!',
		successRegister: 'Вы прошли регистрацию успешно!',
		successProductAdd: 'Товар успешно добавлен!',
		successLocationCreate: 'Населенный пункт успешно добавлен!',
		successLocationRemove: 'Населенный пункт успешно удален',
		successBranchCreate: 'Филиал успешно создан',
		successBranchRemove: 'Филиал успешно удален',
		successAdminCreate: 'Менеджер успешно создан',
		successAdminRemove: 'Менеджер успешно удален',
		noData: 'Нет данных',
		someUnexceptableError: 'Упс... Возникла непредвиденная ошибка',
		successProductRegistered: 'Товар зарегистрирован',
		loginError: 'Вы ввели неверный пароль',
		pageNotFound: 'Страница не найдена',
	},
	places: {
		CHINA: 'Китай',
		BORDER: 'Город',
		KZ: 'Филиал',
	},
	errors: {
		Required: 'Это поле является обязательным',
		'The passwords did not match': 'Пароли не совпадают',
		'Invalid email': 'Невалидный емейл',
		'Invalid input': 'Недопустимый формат поля',
		'String must contain at most 150 character(s)':
			'Строка должна содержать не более 150 символов',
		'String must contain at most 700 character(s)':
			'Строка должна содержать не более 700 символов',
		'String must contain at most 200 character(s)':
			'Строка должна содержать не более 200 символов',
		'String must contain at most 500 character(s)':
			'Строка должна содержать не более 500 символов',
		'String must contain at least 4 character(s)':
			'Строка должна содержать не менее 4 символов',
		'String must contain at least 10 character(s)':
			'Строка должна содержать не менее 10 символов',
		'String must contain at least 1 character(s)': 'Строка должна содержать не менее 1 символа',
		maxMass: 'Указанное значение превышает максимальное допустимое значение',
		'Phone number is already in use!': 'Указанный номер уже занят!',
	},
}
