export default {
  welcome: 'Привет',
  titles: {
    faq: 'FAQ',
    addProduct: 'Добавление товара',
    locations: 'Населенные пункты',
    branches: 'Филиалы',
    personal: 'Менеджеры',
    checkProduct: 'Трекинг товара'
  },
  pages: {
    login: 'Войти',
    register: 'Авторизоватся',
    user: 'Добавление товара',
    productList: 'Список моих товаров',
    info: 'Информация о филиале',
    calculation: 'Калькулятор',
    locations: 'Населенные пункты',
    branchs: 'Филиалы',
    personals: 'Менеджеры',
    products: 'Товары',
    users: 'Пользователи',
    checkProduct: 'Трекинг товара',
    settings: 'Настройки',
  },
  labels: {
    registerMsg: 'Регистрация',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'E-mail',
    phoneNumber: 'Номер телефона',
    password: 'Пароль',
    confirmPassword: 'Повтор пароля',
    selectCity: 'Выбрать населенный пункт',
    selectBranch: 'Выбрать филиал',
    trackCode: 'Трек код',
    description: 'Описание',
    massCount: 'Вес (кг)',
    rate: 'Курс валюты',
    productMass: 'Вес товара',
    cityName: 'Наименование населенного пункта',
    cityType: 'Местоположение населенного пункта',
    branchName: 'Наименование филиала',
    branchAddress: 'Адрес филиала',
    city: 'Город',
    unlock: 'Разблокировать',
    lock: 'Блокировать',
    autoFetch: 'Включить авторегистрацию',
  },
  commands: {
    submit: 'Отправить',
    logout: 'Выйти',
    clear: 'Очистить',
    select: 'Выбрать',
    update: 'Обновить',
    goBack: 'Вернутся назад',
  },
  messages: {
    successRegister: 'Вы прошли регистрацию успешно!',
    successProductAdd: 'Населенный пункт успешно создан',
    successLocationRemove: 'Населенный пункт успешно удален',
    successBranchCreate: 'Филиал успешно создан',
    successBranchRemove: 'Филиал успешно удален',
    successAdminCreate: 'Менеджер успешно создан',
    successAdminRemove: 'Менеджер успешно удален',
    noData: 'Нет данных',
    someUnexceptableError: 'Упс... Возникла непредваденная ошибка',
    successProductRegistered: 'Товар зарегистрирован'
  },
  places: {
    CHINA: 'В Китае',
    BORDER: 'На границе',
    KZ: 'В Казахстане',
  }
}
