export const TEST_REFERALS = [
	{
		id: 1,
		firstName: 'John',
		lastName: 'Doe',
		active: true,
		level: 'bronze',
		referals: 3,
	},
	{
		id: 2,
		firstName: 'Jane',
		lastName: 'Smith',
		active: false,
		level: 'silver',
		referals: 7,
	},
	{
		id: 3,
		firstName: 'Michael',
		lastName: 'Johnson',
		active: true,
		level: 'gold',
		referals: 15,
	},
	{
		id: 4,
		firstName: 'Emily',
		lastName: 'Davis',
		active: true,
		level: 'platinum',
		referals: 20,
	},
	{
		id: 5,
		firstName: 'David',
		lastName: 'Brown',
		active: false,
		level: 'diamond',
		referals: 25,
	},
	{
		id: 6,
		firstName: 'Sarah',
		lastName: 'Wilson',
		active: true,
		level: 'bronze',
		referals: 2,
	},
	{
		id: 7,
		firstName: 'Robert',
		lastName: 'Taylor',
		active: false,
		level: 'silver',
		referals: 6,
	},
	{
		id: 8,
		firstName: 'Jessica',
		lastName: 'Anderson',
		active: true,
		level: 'gold',
		referals: 12,
	},
	{
		id: 9,
		firstName: 'Daniel',
		lastName: 'Thomas',
		active: true,
		level: 'platinum',
		referals: 18,
	},
	{
		id: 10,
		firstName: 'Laura',
		lastName: 'Jackson',
		active: false,
		level: 'diamond',
		referals: 30,
	},
	{
		id: 11,
		firstName: 'Matthew',
		lastName: 'White',
		active: true,
		level: 'bronze',
		referals: 4,
	},
	{
		id: 12,
		firstName: 'Karen',
		lastName: 'Harris',
		active: true,
		level: 'silver',
		referals: 8,
	},
	{
		id: 13,
		firstName: 'James',
		lastName: 'Martin',
		active: false,
		level: 'gold',
		referals: 10,
	},
	{
		id: 14,
		firstName: 'Elizabeth',
		lastName: 'Thompson',
		active: true,
		level: 'platinum',
		referals: 22,
	},
	{
		id: 15,
		firstName: 'Joshua',
		lastName: 'Garcia',
		active: false,
		level: 'diamond',
		referals: 27,
	},
	{
		id: 16,
		firstName: 'Mary',
		lastName: 'Martinez',
		active: true,
		level: 'bronze',
		referals: 5,
	},
	{
		id: 17,
		firstName: 'Christopher',
		lastName: 'Robinson',
		active: false,
		level: 'silver',
		referals: 9,
	},
	{
		id: 18,
		firstName: 'Patricia',
		lastName: 'Clark',
		active: true,
		level: 'gold',
		referals: 14,
	},
	{
		id: 19,
		firstName: 'Thomas',
		lastName: 'Rodriguez',
		active: true,
		level: 'platinum',
		referals: 19,
	},
	{
		id: 20,
		firstName: 'Barbara',
		lastName: 'Lewis',
		active: false,
		level: 'diamond',
		referals: 35,
	},
]
